version: '3.1'

services:
  db:
    container_name: postgres_database
    image: postgres:15.3-alpine3.18
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=manager
    ports:
      - "5432:5432"